CREATE UNLOGGED TABLE IF NOT EXISTS staging.u_addresses (
    id INT PRIMARY KEY,
    alternate_address VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    geom GEOMETRY(POINT, 3765) NOT NULL
);