# Generated by Django 5.2.7 on 2025-11-18 23:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('house_number', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=3765)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': '"rpj"."addresses"',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_number', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': '"dkp"."buildings"',
                'ordering': ('building_number',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CadastralMunicipality',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('national_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('harmonization_status', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'Cadastral Municipality',
                'verbose_name_plural': 'Cadastral Municipalities',
                'db_table': '"dkp"."cadastral_municipalities"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CadastralParcel',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parcel_code', models.CharField(max_length=20)),
                ('graphical_area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'Cadastral Parcel',
                'verbose_name_plural': 'Cadastral Parcels',
                'db_table': '"dkp"."cadastral_parcels"',
                'ordering': ('parcel_code',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('national_code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
                'db_table': '"rpj"."country"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('national_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': '"rpj"."counties"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('national_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': '"rpj"."municipalities"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostalOffice',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('postal_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Postal Office',
                'verbose_name_plural': 'Postal Offices',
                'db_table': '"rpj"."postal_offices"',
                'ordering': ('postal_code',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('national_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3765)),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'db_table': '"rpj"."settlements"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('updated_at', models.DateTimeField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unique_identifier', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'db_table': '"rpj"."streets"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StreetFeature',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unique_identifier', models.BigIntegerField()),
                ('settlement_code', models.IntegerField()),
                ('settlement_name', models.CharField(max_length=255)),
                ('municipality_name', models.CharField(max_length=255)),
                ('county_name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=3765)),
            ],
            options={
                'verbose_name': 'Street (materialized view)',
                'verbose_name_plural': 'Streets (materialized view)',
                'db_table': '"gs"."mv_streets"',
                'ordering': ('name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Usage',
                'verbose_name_plural': 'Usages',
                'db_table': '"dkp"."usages"',
                'ordering': ('code',),
                'managed': False,
            },
        ),
    ]
